name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, self-hosted]

    steps:

    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Build --release
      run: cargo build --verbose --release

    - uses: actions/upload-artifact@v2
      with:
        name: artifact-${{ matrix.os }}
        path: |
          target/release/rust-guessing-game
          target/release/rust-guessing-game.exe
